title: Chris Neighbor # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Masters student at Portland State University majoring in Electrical Engineering in the signal processing and machine learning track, with a background in bioengineering. Working in a graduate research assistantship in molecular computing and machine learning. Graduating in March 2020. 
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/chrisneighbor/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
